name: Cypress Tests

on:
  push:
    branches-ignore:
      - "renovate/**"

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - name: setting hangul
        run: |
          sudo apt-get update
          sudo apt-get install libfontenc1 libxfont1 xfonts-encodings xfonts-utils xfonts-base xfonts-75dpi
          sudo apt-get install -y language-pack-ko
          sudo locale-gen ko_KR.UTF-8
          # Instead of using vi, we'll use echo to append to the file
          echo "export LANG=ko_KR.UTF-8" | sudo tee -a /etc/default/locale
          reboot
      - name: install
        run: yarn
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: yarn dev
          wait-on: "http://localhost:3000"
          browser: chrome
          config: baseUrl=http://localhost:3000
        continue-on-error: true
      - name: Save screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: cypress-image-diff-screenshots/comparison/
