name: Cypress Tests

on:
  push:
    branches-ignore:
      - "renovate/**"

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - name: install
        run: yarn
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: yarn dev
          wait-on: "http://localhost:3000"
          browser: chrome
          config: baseUrl=http://localhost:3000
        continue-on-error: true
      - name: Save screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: cypress-image-diff-screenshots/comparison/
